---
- hosts: localhost
  tasks:
    - name: Write nginx tag into inventory (Can be avoided if the public ip is inserted into inventory manually)
      lineinfile: dest='/etc/ansible/hosts'
        regexp="[nginx]"
        insertafter=EOF
        line="[nginx]"
        state=present

    - name: Lets wait for this hack
      wait_for:
        path: /etc/ansible/hosts
        search_regex: "[nginx]"

    - name: Write inventory to avoid manual intervention (Can be avoided if the public ip is inserted into inventory manually)
      lineinfile: dest='/etc/ansible/hosts'
        regexp="{{ item.public_ip }}"
        insertafter="[nginx]"
        line="{{ item.public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{ local_path }}{{ aws_key_name }}.pem ansible_python_interpreter=/usr/bin/python3"
        state=present
      with_items: "{{ ec2_instance.instances }}"

    - name: Lets wait for this hack
      wait_for:
        path: /etc/ansible/hosts
        search_regex: "{{ item.public_ip }}"
      with_items: "{{ ec2_instance.instances }}"
