---
- hosts: localhost
  tasks:
    - name: Create a EC2 key pair in AWS
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_material: "{{ ssh_key_material }}"
      register: ec2_key

    - name: Save self created key to local path
      copy: content="{{ local_path }}{{ key_name }}.pub" dest="{{ local_path }}{{ key_name }}.pem" mode=0600
      when: ec2_key.changed
