---
- hosts: nginx
  become: yes
  tasks:
    - name: Install Nginx web server
      apt: pkg=nginx state=installed update_cache=true

    - name: Upload default index.html for host
      copy: src="{{ local_path}}/index.html" dest=/usr/share/nginx/html/ mode=0644

    - name: Start Nginx
      service: name=nginx state=started
